language: java
script: mvn clean install -Ptravis
# Remove --quiet to avoid timeouts
install: mvn install -DskipTests=true

notifications:
  email:
    - kill-bill-commits@googlegroups.com

jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7

env:
  - MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"

# attempt to fix build (see: https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913)
addons:
  hosts:
    - myshorthost
  hostname: myshorthost
